version: "3.3"

services:
  postgres:
    image: postgres
    environment: &postgres_env
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./postgres/mount:/var/lib/postgresql/data
  server:
    build: .
    command: hypercorn --bind 0.0.0.0:8000 src.api.main:app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      <<: *postgres_env
      POSTGRES_URL: $POSTGRES_URL
      SECRET_KEY: $SECRET_KEY
      ALGORITHM: $ALGORITHM
      ACCESS_TOKEN_EXPIRE_MINUTES: $ACCESS_TOKEN_EXPIRE_MINUTES
    volumes:
    - ./files:/server/src/files
  telegram:
    build: telegram_bot/
    command: python3 bot.py
    environment:
      TG_BOT_TOKEN: $TG_BOT_TOKEN
      HOST: $HOST
    depends_on:
      - postgres
      - server